### ISSUE TITLE
Minimal script/notebook available for testing performance on the GLaS dataset?

### ISSUE THREAD

**Issue by ajinkya-kulkarni** [dakomura/SegPath_code#2]
Hello team, thanks for this repo! I was wondering if there is any minimal script/notebook available for testing performance on the GLaS dataset? I have a bunch of HE images similar to images in the GLaS dataset, and I would like to test your trained model to segment glands. 

Thanks!
Ajinkya

**Comment by dakomura** [comment]
Hi @ajinkya-kulkarni ,

Thank you for reaching out! 

The evaluation code for the GLaS dataset is a part of a larger codebase that includes a DALI-based dataloader and integration of outputs from multiple models. Extracting a minimal script or notebook from it will take some time. Could you please clarify if there are any specific processes you particularly need? If you need code snippets for particular processes, we might be able to provide them more quickly.

Daisuke
