### ISSUE TITLE
missing functions in registration 

### ISSUE THREAD

**Issue by wooginawunan** [dakomura/SegPath_code#5]
Hi,

Thank you for providing the nice implementation.

I am trying to replicate/run from the beginning, of registration. 
However, i found two missing pieces:
- https://github.com/dakomura/SegPath_code/blob/9925a24caadc718629245be68cd5eec742021ca0/utils/registration.py#L13C18-L13C31
- https://github.com/dakomura/SegPath_code/blob/9925a24caadc718629245be68cd5eec742021ca0/utils/registration.py#L108

`rgb2hed_split ` can be found in `stain.py` but the second one `self.first_registration` is not found anywhere.

Thanks

**Comment by dakomura** [comment]
Hi @wooginawunan,

Thank you for pointing out the bug. 

I have changed `rgb2hed_split` to be imported from `stain.py`. 
Also, `first_registration` should have been `rigid_registration`, so I have corrected that as well.
